// ================= TGF Series HVAC Data =================

const tgfData = {
    name: "TGF Series",
    description: "Carrier TGF Series - 1-Way Cassette, Under Ceiling, 4-Way Cassette, Ducted",
    pdfUrl: "Carrier-42TGF-CP-Catalog.pdf",
    models: {
        "42TGF0131UP": {
            "Type": "1-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0131A1",
            "NominalCoolingCapacity": 13300,
            "SEER": 14.77,
            "PowerConsumption": 1.30,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 4.85,
            "Indoor_Height_mm": 250,
            "Indoor_Width_mm": 780,
            "Indoor_Depth_mm": 430,
            "Outdoor_Height_mm": 530,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 16,
            "Weight_Outdoor_kg": 33,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "42TGF0181UP": {
            "Type": "1-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0181A1",
            "NominalCoolingCapacity": 18700,
            "SEER": 13.70,
            "PowerConsumption": 1.39,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 6.85,
            "Indoor_Height_mm": 250,
            "Indoor_Width_mm": 780,
            "Indoor_Depth_mm": 430,
            "Outdoor_Height_mm": 550,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 16,
            "Weight_Outdoor_kg": 37,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "42TGF0241UP": {
            "Type": "1-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0241A1",
            "NominalCoolingCapacity": 24200,
            "SEER": 13.70,
            "PowerConsumption": 2.00,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 9.50,
            "Indoor_Height_mm": 250,
            "Indoor_Width_mm": 1074,
            "Indoor_Depth_mm": 703,
            "Outdoor_Height_mm": 550,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 26,
            "Weight_Outdoor_kg": 38,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0301UP": {
            "Type": "1-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0301A1",
            "NominalCoolingCapacity": 30000,
            "SEER": 13.69,
            "PowerConsumption": 2.50,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 12.00,
            "Indoor_Height_mm": 270,
            "Indoor_Width_mm": 1074,
            "Indoor_Depth_mm": 703,
            "Outdoor_Height_mm": 630,
            "Outdoor_Width_mm": 800,
            "Outdoor_Depth_mm": 300,
            "Weight_Indoor_kg": 30,
            "Weight_Outdoor_kg": 40,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0361UP": {
            "Type": "1-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0361A1",
            "NominalCoolingCapacity": 36100,
            "SEER": 13.12,
            "PowerConsumption": 3.09,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 14.50,
            "Indoor_Height_mm": 310,
            "Indoor_Width_mm": 1384,
            "Indoor_Depth_mm": 703,
            "Outdoor_Height_mm": 890,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 48,
            "Weight_Outdoor_kg": 57,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0361UP_3PH": {
            "Type": "1-Way Cassette (3 Ph)",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0361A3",
            "NominalCoolingCapacity": 36100,
            "SEER": 13.12,
            "PowerConsumption": 3.09,
            "NominalVoltage": 380,
            "NumberofPhases": 3,
            "NominalFrequency": 50,
            "OperatingCurrent": 5.50,
            "Indoor_Height_mm": 310,
            "Indoor_Width_mm": 1384,
            "Indoor_Depth_mm": 703,
            "Outdoor_Height_mm": 890,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 48,
            "Weight_Outdoor_kg": 57,
            "RefrigerantType": "R32",
            "CompressorType": "Scroll",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0401UP_3PH": {
            "Type": "1-Way Cassette (3 Ph)",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0401A3",
            "NominalCoolingCapacity": 40200,
            "SEER": 13.69,
            "PowerConsumption": 3.44,
            "NominalVoltage": 380,
            "NumberofPhases": 3,
            "NominalFrequency": 50,
            "OperatingCurrent": 6.38,
            "Indoor_Height_mm": 310,
            "Indoor_Width_mm": 1384,
            "Indoor_Depth_mm": 703,
            "Outdoor_Height_mm": 890,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 48,
            "Weight_Outdoor_kg": 69,
            "RefrigerantType": "R32",
            "CompressorType": "Scroll",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0131CP": {
            "Type": "Under Ceiling",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0131A1",
            "NominalCoolingCapacity": 13300,
            "SEER": 14.48,
            "PowerConsumption": 1.05,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 4.85,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 950,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 530,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 23,
            "Weight_Outdoor_kg": 33,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "42TGF0181CP": {
            "Type": "Under Ceiling",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0181A1",
            "NominalCoolingCapacity": 18700,
            "SEER": 14.48,
            "PowerConsumption": 1.48,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 7.10,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 950,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 550,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 23,
            "Weight_Outdoor_kg": 37,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "42TGF0241CP": {
            "Type": "Under Ceiling",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0241A1",
            "NominalCoolingCapacity": 24200,
            "SEER": 13.17,
            "PowerConsumption": 2.00,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 9.50,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 1270,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 550,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 29,
            "Weight_Outdoor_kg": 37,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "5/8"
        },
        "42TGF0301CP": {
            "Type": "Under Ceiling",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0301A1",
            "NominalCoolingCapacity": 30000,
            "SEER": 13.80,
            "PowerConsumption": 2.55,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 12.00,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 1270,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 630,
            "Outdoor_Width_mm": 800,
            "Outdoor_Depth_mm": 300,
            "Weight_Indoor_kg": 29,
            "Weight_Outdoor_kg": 40,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0361CP": {
            "Type": "Under Ceiling",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0361A1",
            "NominalCoolingCapacity": 36100,
            "SEER": 12.56,
            "PowerConsumption": 3.44,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 16.00,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 1580,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 890,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 37,
            "Weight_Outdoor_kg": 57,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "42TGF0601CP_3PH": {
            "Type": "Under Ceiling (3 Ph)",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0601A3",
            "NominalCoolingCapacity": 60000,
            "SEER": 10.58,
            "PowerConsumption": 5.80,
            "NominalVoltage": 380,
            "NumberofPhases": 3,
            "NominalFrequency": 50,
            "OperatingCurrent": 9.50,
            "Indoor_Height_mm": 235,
            "Indoor_Width_mm": 1580,
            "Indoor_Depth_mm": 690,
            "Outdoor_Height_mm": 1340,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 37,
            "Weight_Outdoor_kg": 94,
            "RefrigerantType": "R32",
            "CompressorType": "Scroll",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "3/4"
        },
        "40TGF0131UP": {
            "Type": "4-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0131A1",
            "NominalCoolingCapacity": 13300,
            "SEER": 13.46,
            "PowerConsumption": 1.05,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 4.85,
            "Indoor_Height_mm": 256,
            "Indoor_Width_mm": 840,
            "Indoor_Depth_mm": 840,
            "Outdoor_Height_mm": 530,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 20,
            "Weight_Outdoor_kg": 33,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "40TGF0361UP": {
            "Type": "4-Way Cassette",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0361A1",
            "NominalCoolingCapacity": 36100,
            "SEER": 12.56,
            "PowerConsumption": 3.09,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 14.50,
            "Indoor_Height_mm": 319,
            "Indoor_Width_mm": 840,
            "Indoor_Depth_mm": 840,
            "Outdoor_Height_mm": 890,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 24,
            "Weight_Outdoor_kg": 57,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "5/8"
        },
        "40TGF0601UP_3PH": {
            "Type": "4-Way Cassette (3 Ph)",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0601A3",
            "NominalCoolingCapacity": 60000,
            "SEER": 11.14,
            "PowerConsumption": 5.50,
            "NominalVoltage": 380,
            "NumberofPhases": 3,
            "NominalFrequency": 50,
            "OperatingCurrent": 9.80,
            "Indoor_Height_mm": 319,
            "Indoor_Width_mm": 840,
            "Indoor_Depth_mm": 840,
            "Outdoor_Height_mm": 1340,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 24,
            "Weight_Outdoor_kg": 94,
            "RefrigerantType": "R32",
            "CompressorType": "Scroll",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "3/4"
        },
        "42TGF0131BP": {
            "Type": "Duct Type",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0131A1",
            "NominalCoolingCapacity": 13300,
            "SEER": 13.46,
            "PowerConsumption": 1.17,
            "NominalVoltage": 220,
            "NumberofPhases": 1,
            "NominalFrequency": 50,
            "OperatingCurrent": 5.40,
            "Indoor_Height_mm": 275,
            "Indoor_Width_mm": 700,
            "Indoor_Depth_mm": 750,
            "Outdoor_Height_mm": 530,
            "Outdoor_Width_mm": 780,
            "Outdoor_Depth_mm": 290,
            "Weight_Indoor_kg": 23,
            "Weight_Outdoor_kg": 33,
            "RefrigerantType": "R32",
            "CompressorType": "Rotary",
            "Pipe_Liquid": "1/4",
            "Pipe_Suction": "1/2"
        },
        "42TGF0601BP_3PH": {
            "Type": "Duct Type (3 Ph)",
            "Brand": "Carrier",
            "Series": "TGF Series",
            "Outdoor_Model": "38TGF0601A3",
            "NominalCoolingCapacity": 60000,
            "SEER": 11.14,
            "PowerConsumption": 5.60,
            "NominalVoltage": 380,
            "NumberofPhases": 3,
            "NominalFrequency": 50,
            "OperatingCurrent": 9.70,
            "Indoor_Height_mm": 275,
            "Indoor_Width_mm": 1400,
            "Indoor_Depth_mm": 750,
            "Outdoor_Height_mm": 1340,
            "Outdoor_Width_mm": 900,
            "Outdoor_Depth_mm": 320,
            "Weight_Indoor_kg": 41,
            "Weight_Outdoor_kg": 94,
            "RefrigerantType": "R32",
            "CompressorType": "Scroll",
            "Pipe_Liquid": "3/8",
            "Pipe_Suction": "3/4"
        }
    }
};

// ================= IFC Data Transformation =================

function getTgfIfcData(modelId) {
    const data = tgfData.models[modelId];
    if (!data) return null;

    const realModelId = modelId.replace("_3PH", "");

    return [
        { group: "Identity", property: "IfcEntityType", value: "IfcUnitaryControlElement" },
        { group: "Identity", property: "IfcTag", value: realModelId },
        { group: "Identity", property: "ObjectType", value: data.Type },
        { group: "Pset_ManufacturerTypeInformation", property: "Manufacturer", value: data.Brand },
        { group: "Pset_ManufacturerTypeInformation", property: "ModelReference", value: realModelId },
        { group: "Pset_AirConditioningUnit", property: "NominalCoolingCapacity", value: data.NominalCoolingCapacity + " BTU/hr" },
        { group: "Pset_AirConditioningUnit", property: "RefrigerantType", value: data.RefrigerantType },
        { group: "Pset_ElectricalDeviceCommon", property: "NominalVoltage", value: data.NominalVoltage + " V" },
        { group: "Pset_ElectricalDeviceCommon", property: "NumberofPhases", value: data.NumberofPhases },
        { group: "Pset_ElectricalDeviceCommon", property: "NominalFrequency", value: data.NominalFrequency + " Hz" },
        { group: "Pset_Carrier_Custom_Specs", property: "Outdoor_Model", value: data.Outdoor_Model },
        { group: "Pset_Carrier_Custom_Specs", property: "SEER", value: data.SEER },
        { group: "Pset_Carrier_Custom_Specs", property: "PowerConsumption", value: data.PowerConsumption + " kW" },
        { group: "Pset_Carrier_Custom_Specs", property: "OperatingCurrent", value: data.OperatingCurrent + " A" },
        { group: "Pset_Carrier_Custom_Specs", property: "Indoor_Dimensions_mm", value: `${data.Indoor_Height_mm} x ${data.Indoor_Width_mm} x ${data.Indoor_Depth_mm}` },
        { group: "Pset_Carrier_Custom_Specs", property: "Outdoor_Dimensions_mm", value: `${data.Outdoor_Height_mm} x ${data.Outdoor_Width_mm} x ${data.Outdoor_Depth_mm}` },
        { group: "Pset_Carrier_Custom_Specs", property: "Weight_Indoor_kg", value: data.Weight_Indoor_kg },
        { group: "Pset_Carrier_Custom_Specs", property: "Weight_Outdoor_kg", value: data.Weight_Outdoor_kg },
        { group: "Pset_Carrier_Custom_Specs", property: "Pipe_Liquid_inch", value: data.Pipe_Liquid },
        { group: "Pset_Carrier_Custom_Specs", property: "Pipe_Suction_inch", value: data.Pipe_Suction },
        { group: "Pset_Carrier_Custom_Specs", property: "CompressorType", value: data.CompressorType }
    ];
}

function getTgfModelList() {
    return Object.keys(tgfData.models).sort();
}
